### ISSUE TITLE
Overlay socket is hardcoded to connect to `ws://localhost:8081`

### ISSUE THREAD

**Issue by G-Rath** [G-Rath/webpack-serve-overlay#1]
Currently the WebSocket in the overlay [is hardcoded](https://github.com/G-Rath/webpack-serve-overlay/blob/b38c0d411e2061d762125b33c917c407fd4925d4/errorOverlay.js#L121) to connect to `ws://localhost:8081`, which is clearly dumb.

Ideally this should use the same mechanism as `webpack-serve` does for it's socket.

It'd be nice if this was at least something that could be configured as an option in the webpack config itself somehow.

**Comment by chanon** [comment]
I am new to `webpack-serve`, but the websocket port it uses changes every time I run it. How would I get `webpack-serve-overlay` to use the same port?

Or is there a way to config the `webpack-serve` websocket port so I can set it to always be 8081? As it is, it seems impossible to use this.

**Comment by G-Rath** [comment]
@chanon This is the feature I want to get sorted the most for this package. Currently you can set the url via the `WEBPACK_SERVE_OVERLAY_WS_URL` env value.

I find `webpack-serve` uses a random port under a few conditions, such as when the desired port is already in use.

You can target specific ports via options in the `serve` configuration.

Here's how mine looks:
```
module.exports.serve = {
    port: 3334,
    hotClient: {
        port: {
            client: 8081,
            server: 8081
        }
    },
    clipboard: false,
    logTime: false,
    content: [__dirname]
};
```

The above has `webpack-serve` run on port `3334`, while the hotclient targets port `8081`, which is what the overlay connects to.

I'm yet to find a way for the overlay to automagically detect what ports `webpack-serve` (& co, since I think technically this lies with the `webpack-hot-client` package) are using, but @shellscape might have an idea on how to do that.

Ideally, I'd love it if `webpack-serve` exposed the ports via `process.env`, since then it'd just be a matter of having ```const ws = new WebSocket(`ws://localhost:${process.env.WEBPACK_SERVE_HOT_CLIENT_PORT}');```, with no additional fuss.

**Comment by shellscape** [comment]
Checkout this line: https://github.com/webpack-contrib/webpack-hot-client/blob/master/lib/client/index.js#L14 - You might be able to use the same `__hotClientOptions__` identifier and get a copy of the options since you're going to be part of the bundle. The `DefinePlugin` added in webpack-hot-client takes care of passing the options to client in that way.

**Comment by G-Rath** [comment]
That works perfectly, thanks - exactly what I wanted!

That pretty much lets me solve most of the things I wanted for this overlay, since I can use the same logic as `webpack-hot-client` to get things like the url as well.

I'll write up a fix right now.

**Comment by shellscape** [comment]
Awesome. For what it's worth, I'm planning on contributing to your project in the near future. I got a little derailed by a thumb with many stitches and some life happenings (you may have noticed I haven't been as active on webpack-serve in the last month).

**Comment by G-Rath** [comment]
Released in v0.3.0

@chanon you should now no longer have to specify anything extra, aside from including the overlay in your `index.jsx` file for it to work.

@shellscape thanks for your help. I think the overlay is now pretty much feature complete, so unless anything else comes up in the next couple of days, I'll likely just release v1.

Let me know if you've got any newbie-safe `webpack-contrib` stuff you'd like a hand with - I'd be happy to lend a hand where I can.

^^ I was writing this when you replied 😂

Here's my reply to yours: 

Sounds painful 😱 

As I said, I'm pretty happy with the overlay as it is, so if you have any features or suggestions on how to improve it, feel free to create issues, but aside from that, I don't anticipate much working actually needing to be done on it now.

**Comment by shellscape** [comment]
I've got a few ideas for tasty tidbits :smile:  (Of course would totally be your call to include them)

Life's curveballs have me pulled away from a lot of webpack-contrib work right now (and every other project I'm involved in). If you want to get your hands dirty, there are a few PRs and issues that need triaging in webpack-serve and webpack-hot-client that I just can't get to at the moment.

**Comment by G-Rath** [comment]
I'm always keen for tidbits - the tastier the better 😀

I never can refuse an invitation for a good hand dirtying 😉 I'll have a look over the repos when I have a spare few minutes, and see what I can dig up.

**Comment by chanon** [comment]
@G-Rath awesome, thank you! This will be the final touch to my webpack config :)
